example:
  property: '[GIT] licensing-service.yml: DEFAULT'

spring:
  database:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: POSTGRESQL
    show-sql: true

  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: 'SELECT 1'

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: organizationChangeToken:dev.magadiflo.licensing.app.model.dto.OrganizationChange

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
