example:
  property: '[GIT] licensing-service-prod.yml: PROD'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_licensing_service_prod
    username: postgres
    password: '{cipher}e0ba4a95b8f39d620af916c3f633c2abcb2c11b16714d272274cf1b435575206'