server:
  port: 8888
  error:
    include-message: always

# Le dice al servidor de configuración que use este valor como clave simétrica
encrypt:
  key: IMSYMMETRIC

spring:
  application:
    name: config-server
  profiles:
    active: vault, git

  cloud:
    config:
      server:
        vault:
          host: 127.0.0.1
          port: 8200
          kvVersion: 2
          backend: spring-microservices
        git:
          uri: https://github.com/magadiflo/spring-microservices-in-action-2021.git
          searchPaths: config-repo
#        native:
#          search-locations: classpath:/config