server:
  port: 8888
  error:
    include-message: always

# Le dice al servidor de configuración que use este valor como clave simétrica
encrypt:
  key: IMSYMMETRIC

spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config