example:
  property: 'Soy el archivo de propiedad del servicio licensing-service para PROD'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_licensing_service_prod
    username: postgres
    password: magadiflo