example:
  property: '[classpath:/config] licensing-service.yml: DEFAULT'

spring:
  database:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: POSTGRESQL
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8181/realms/spmia-realm

  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: 'SELECT 1'

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/