example:
  property: '[classpath:/config] licensing-service-prod.yml: PROD'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_licensing_service_prod
    username: postgres
    password: magadiflo