server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8181/realms/spmia-realm

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: organizationChangeModelToken:dev.magadiflo.organization.app.model.dto.OrganizationChangeModel

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    dev.magadiflo: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/