spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      token: myroot

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: ALWAYS
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true