server:
  error:
    include-message: always

spring:
  application:
    name: gateway-server

  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.web: WARN
    dev.magadiflo: DEBUG